name: flutter_web.examples.flex_playground
dependencies:
  flutter_web: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any

dependency_overrides:
  flutter_web:
    path: ../../packages/flutter_web
  flutter_web_ui:
    path: ../../packages/flutter_web_ui
