name: flutter_web_ui
version: 0.0.1
author: Dart Team <web@dartlang.org>
description: >
  An implementation of dart:ui for web.
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter_web:
    path: ../flutter_web
  collection: ^1.0.0
  meta: ^1.1.5
  vector_math: ^2.0.7
  intl: any
dev_dependencies:
  flutter_web_test:
    path: ../flutter_web_test
  test: ^1.3.0
