name: flutter_web.examples.hello_world
dependencies:
  flutter_web:
    path: ../../flutter_web
  flutter_web_ui:
    path: ../../flutter_web_ui
dev_dependencies:
  build_runner: any
  build_web_compilers: any
