name: slide_puzzle

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  pedantic: ^1.3.0

  build_runner: ^1.2.2
  build_web_compilers: ^1.1.0

dependency_overrides:
  flutter_web:
    path: ../../packages/flutter_web
  flutter_web_ui:
    path: ../../packages/flutter_web_ui
