name: flutter_web_test
version: 0.0.3-alpha
author: Dart Team <web@dartlang.org>
description: >
  A test framework for Dart based on Flutter's development model.
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter_web:
    path: ../flutter_web
  collection: ^1.0.0
  intl: ^0.15.7
  meta: ^1.1.5
  quiver: ^2.0.1
  vector_math: ^2.0.7
dev_dependencies:
  test: ^1.3.0
