name: flutter_web.examples.spinning_square

dependencies:
  flutter_web: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any

dependency_overrides:
  flutter_web:
    path: ../../flutter_web
  flutter_web_ui:
    path: ../../flutter_web_ui
