# See https://github.com/dart-lang/build/tree/master/build_web_compilers#configuration
targets:
  $default:
    builders:
      build_web_compilers|dart2js_archive_extractor:
        options:
          # Ensures .info.json file is preserved. Useful for tracking output details.
          filter_outputs: false
      build_web_compilers|entrypoint:
        generate_for:
        - web/**.dart
        options:
          dart2js_args:
            # Generate `.info.json` files for compiled libraries.
            - --dump-info
            # Reduces diffs between builds, but increases JS output size slightly.
            - --no-frequency-based-minification
            # Deployed example does not include Dart source. Not needed.
            - --no-source-maps
            # Enable all dart2js optimizations. Not recommended without thorough testing.
            - -O4
