targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
          #- --minify
          #- --fast-startup
          - --omit-implicit-checks
          - --trust-primitives
